package:
  name: teexpo
  version: "1.0.0"

source:
  url: https://github.com/ausswal/TEexpo/archive/refs/tags/v1.0.0.tar.gz
  sha256sum v1.0.0.tar.gz

build:
  number: 0
  noarch: generic
  run_exports: []

requirements:
  host:
    - python 3.10
    - pip
  run:
    - python >=3.10,<3.11
    - pandas
    - matplotlib-base
    - hmmer >=3.3
    - repeatmasker
    - repeatmodeler
    - bedtools
    - seqkit
    - cd-hit
    - mafft
    - trimal
    - emboss
    - trnascan-se
    - genometools-genometools >=1.6.5
    - vsearch
    - transposonpsi
    - samtools
    - pyfiglet

test:
  commands:
    - teexpo --help
    - teexpo --version
    - cons -help || true

about:
  home: https://github.com/ausswal/TEexpo
  dev_url: https://github.com/ausswal/TEexpo
  summary: "TEexpo: Automated and curated transposable element annotation pipeline"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Swarup Das